# Generated by Django 4.0.5 on 2022-06-09 13:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('roll_no', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('homecity', models.CharField(max_length=100)),
                ('qualities', models.TextField()),
                ('previous_experience', models.TextField()),
                ('dish_describe', models.TextField()),
                ('qualities_for_core', models.TextField()),
                ('upcoming_event_desired', models.TextField()),
            ],
        ),
    ]
